### ISSUE TITLE
Unexpected COMPARE error

### ISSUE THREAD

**Issue by kiote** [MaxSvargal/node-vk-music-sync#1]
When executing vksync I have an error:

```
/usr/local/lib/node_modules/node-vk-music-sync/node_modules/coffee-script/lib/coffee-script/helpers.js:200
    throw error;
          ^
SyntaxError: unexpected COMPARE
    at Object.exports.throwSyntaxError (/usr/local/lib/node_modules/node-vk-music-sync/node_modules/coffee-script/lib/coffee-script/helpers.js:197:13)
    at Object.parser.yy.parseError (/usr/local/lib/node_modules/node-vk-music-sync/node_modules/coffee-script/lib/coffee-script/coffee-script.js:265:20)
    at Object.parse (/usr/local/lib/node_modules/node-vk-music-sync/node_modules/coffee-script/lib/coffee-script/parser.js:537:22)
    at exports.compile.compile (/usr/local/lib/node_modules/node-vk-music-sync/node_modules/coffee-script/lib/coffee-script/coffee-script.js:35:24)
    at Object.loadFile (/usr/local/lib/node_modules/node-vk-music-sync/node_modules/coffee-script/lib/coffee-script/coffee-script.js:176:14)
    at Module.load (/usr/local/lib/node_modules/node-vk-music-sync/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-vk-music-sync/bin/vksync:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

System: MacOS 10.9.3 with npm@1.3.24

**Comment by MaxSvargal** [comment]
The code is obsolete and not supported.
Try to use desktop version https://github.com/MaxSvargal/syncstray

**Comment by kiote** [comment]
cool! I was waiting more than a year for it! Hope it worth it ;)
